<a href="https://colab.research.google.com/github/vishal815/NumpyAndPandasFor-Deep_learning_course-/blob/main/NumpyAndPandasFor(Deep_learning).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist =[1,2,3]
type[mylist]

type[[1, 2, 3]]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
type(list)

type

In [5]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3])

In [7]:
mylist =[[1,2,3],
         [3,4,5],
          [5,6,7]]

In [8]:
mylist

[[1, 2, 3], [3, 4, 5], [5, 6, 7]]

In [9]:
mymatrix = np.array(mylist)
mymatrix.shape

(3, 3)

In [10]:
 np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [12]:
type(x)

numpy.ndarray

In [13]:
np.zeros((4,10))     #tupal

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,4)) + 4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [16]:
[2,1,1]*6

[2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1]

In [17]:
np.linspace(0,9, 20)   #(start , stop, HowMenyNumber)

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [18]:
np.linspace(0,9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.eye(5)  #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3,3)

array([[0.9336219 , 0.14232069, 0.74562282],
       [0.10862431, 0.57276498, 0.57226664],
       [0.17671596, 0.76821255, 0.23137305]])

In [21]:
np.random.randn(5,5)    #noraml distribution

array([[ 1.58396318,  0.56584614, -1.04892435, -0.58816255,  0.46494628],
       [-0.51607201,  0.84072697,  1.58955153,  2.29205719, -0.60834521],
       [ 0.20708785, -0.14302148, -0.21047497,  0.60433492, -1.35169339],
       [ 1.43341362, -0.44203382,  1.15044452, -0.81754961,  0.4936839 ],
       [ 0.40292028,  0.87751552, -1.27310134,  0.54474845,  2.12397302]])

In [22]:
np.random.randn(10)

array([-0.80986432, -0.74403402,  0.31906838,  0.17536421, -0.16004925,
        0.00679627, -1.63140514, -0.67990668,  0.73621792, -0.61601722])

In [23]:
np.random.randint(1,20,10)   #where to where and how meny

array([ 1, 12, 16, 16,  2,  5,  7, 12, 13, 16])

In [24]:
arr=np.random.rand(4)
arr

array([0.00890435, 0.78426113, 0.63347761, 0.6623952 ])

In [25]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)
ranarr

array([18,  9, 36, 27,  2, 31,  1, 11, 21,  8])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.shape

(25,)

In [29]:
#arr.reshape(5,3)  will give error
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([18,  9, 36, 27,  2, 31,  1, 11, 21,  8])

In [31]:
ranarr.max()

36

In [32]:
ranarr.min()

1

In [33]:
ranarr.argmax()

2

In [34]:
ranarr.argmin()

6

**L4**

In [35]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[4]

4

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[5:]    #five to uptoend

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [42]:
arr/2


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [43]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slice_of_array = arr[0:6]
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [46]:
slice_of_array[:] =99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_copy[:]=1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2D


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2D[1]

array([20, 25, 30])

In [53]:
arr_2D[2][2]

45

In [54]:
arr_2D[2,2]

45

In [55]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [56]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [58]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[arr <=2]

array([1, 2])

**Perform some operations**

In [61]:
import numpy as np

In [62]:
arr =np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [64]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [65]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [66]:
(arr +2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [67]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
1/arr

<ipython-input-68-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [69]:
arr/arr

<ipython-input-69-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.log(arr)

<ipython-input-71-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [72]:
sum(arr)

45

In [73]:
arr.max()

9

In [74]:
arr.mean()

4.5

In [75]:
arr_2d =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
arr_2d.shape

(3, 4)

In [77]:
arr_2d.sum(axis=0)    #axis=0 mins virticaly or across row

array([15, 18, 21, 24])

In [78]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [79]:
# **excise **

In [80]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
x=np.ones(5);
x*10

array([10., 10., 10., 10., 10.])

In [82]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [83]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
np.random.rand(1)

array([0.74068147])

In [87]:
(np.arange(1,101).reshape(10,10))/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [88]:
x=np.arange(1,26).reshape(5,5)
x


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [89]:
x[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
x[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [91]:
x[3,4]

20

In [92]:
np.arange(2,13,5)

array([ 2,  7, 12])

In [93]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
x[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [95]:
x.sum()

325

In [96]:
x.sum(axis=0)

array([55, 60, 65, 70, 75])

In [97]:
x.std()

7.211102550927978

**Pandas**
# Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data

In [98]:
import pandas as pd

In [99]:
labels =['a','b','c']   #array

In [100]:
mylist=[10,20,30]

In [101]:
arr=np.array(mylist)
arr

array([10, 20, 30])

In [102]:
d = {'a':10, 'b':20, 'c':30}   #disc
d

{'a': 10, 'b': 20, 'c': 30}

In [103]:
pd.Series(mylist)

0    10
1    20
2    30
dtype: int64

In [104]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [105]:
from re import L
pd.Series(data=arr, index= labels)

a    10
b    20
c    30
dtype: int64

In [106]:
pd.Series(data=['c','d','g'])

0    c
1    d
2    g
dtype: object

In [107]:
ser1=pd.Series([1,8,3,4,5],index=['India','usa','china', 'nepal','pakistan'])

In [108]:
ser1

India       1
usa         8
china       3
nepal       4
pakistan    5
dtype: int64

In [109]:
ser1["India"]

1

In [110]:
ser2=pd.Series([1,6,7,8,9],index=['India','Itli','china', 'jpan','pakistan'])
ser2

India       1
Itli        6
china       7
jpan        8
pakistan    9
dtype: int64

In [111]:
ser1+ser2        #nan+int=nan

India        2.0
Itli         NaN
china       10.0
jpan         NaN
nepal        NaN
pakistan    14.0
usa          NaN
dtype: float64

In [112]:
import pandas as pd
import numpy as np


In [113]:
from numpy.random import randn
np.random.seed(101)

rand_matrix= randn(5,4)
rand_matrix

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [114]:
from pandas.core.roperator import rand_
from numpy.random.mtrand import rand
df=pd.DataFrame(data=rand_matrix, index='A B C D E'.split(), columns='W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [115]:
'A B C D E'.split()


['A', 'B', 'C', 'D', 'E']

In [116]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [117]:
df[['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [118]:
df['new']=df["W"]+df["Y"]       # make a new columan
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [119]:
df.drop('new', axis=1)          #Remove columan

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [120]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [121]:
df.drop('new', axis=1, inplace=True)   #permanet delet
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [122]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

**Operation on Row**

In [123]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [124]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [125]:
#For multipal row
df.loc[['A','B']]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [126]:
df.iloc[[0,3]]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [127]:
df.loc[['A','B']][["Y",'Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965

**Conditional selection**

In [128]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [129]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [130]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [131]:
df['W']>0       #condition

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [132]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [133]:
cond1= df['W']>0
cond2= df['Y']>1
df[(cond1) & (cond2)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [134]:
df[(cond1) | (cond2)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [135]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [136]:
new_ind = "ca ny wy or co".split()
new_ind

['ca', 'ny', 'wy', 'or', 'co']

In [137]:
df['States']= new_ind

In [138]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     ca
B  0.651118 -0.319318 -0.848077  0.605965     ny
C -2.018168  0.740122  0.528813 -0.589001     wy
D  0.188695 -0.758872 -0.933237  0.955057     or
E  0.190794  1.978757  2.605967  0.683509     co

In [139]:
df.set_index('States', inplace=True)    # If we want original data not be changed and new data permanent fit



In [140]:
df

W         X         Y         Z
States                                        
ca      2.706850  0.628133  0.907969  0.503826
ny      0.651118 -0.319318 -0.848077  0.605965
wy     -2.018168  0.740122  0.528813 -0.589001
or      0.188695 -0.758872 -0.933237  0.955057
co      0.190794  1.978757  2.605967  0.683509

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, ca to co
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [142]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [143]:
df['W']>0

States
ca     True
ny     True
wy    False
or     True
co     True
Name: W, dtype: bool

In [144]:
ser_w = df['W']>0

In [145]:
ser_w.value_counts()

True     4
False    1
Name: W, dtype: int64

In [146]:
sum(ser_w)

4

In [147]:
len(ser_w)     #len-sum(true) =false

5

**GroupBy operations**

In [148]:

# Create a pandas DataFrame.
import pandas as pd
technologies   = ({
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas","Hadoop","Spark","Python"],
    'Fee' :[22000,25000,23000,24000,26000,25000,25000,22000],
    'Duration':['30days','50days','35days','40days','60days','35days','55days','50days'],
    'Discount':[1000,2300,1000,1200,2500,1300,1400,1600]
                })
df = pd.DataFrame(technologies, columns=['Courses','Fee','Duration','Discount'])
print(df)


   Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300
2   Hadoop  23000   35days      1000
3   Python  24000   40days      1200
4   Pandas  26000   60days      2500
5   Hadoop  25000   35days      1300
6    Spark  25000   55days      1400
7   Python  22000   50days      1600


In [149]:
df.groupby('Courses')

In [150]:
df.groupby('Courses').mean()

<ipython-input-150-2f0ea21c5f56>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Courses').mean()


Fee  Discount
Courses                   
Hadoop   24000.0    1150.0
Pandas   26000.0    2500.0
PySpark  25000.0    2300.0
Python   23000.0    1400.0
Spark    23500.0    1200.0

In [151]:
df.groupby('Courses').describe()

Fee                                                            \
        count     mean          std      min      25%      50%      75%   
Courses                                                                   
Hadoop    2.0  24000.0  1414.213562  23000.0  23500.0  24000.0  24500.0   
Pandas    1.0  26000.0          NaN  26000.0  26000.0  26000.0  26000.0   
PySpark   1.0  25000.0          NaN  25000.0  25000.0  25000.0  25000.0   
Python    2.0  23000.0  1414.213562  22000.0  22500.0  23000.0  23500.0   
Spark     2.0  23500.0  2121.320344  22000.0  22750.0  23500.0  24250.0   

                 Discount                                                      \
             max    count    mean         std     min     25%     50%     75%   
Courses                                                                         
Hadoop   25000.0      2.0  1150.0  212.132034  1000.0  1075.0  1150.0  1225.0   
Pandas   26000.0      1.0  2500.0         NaN  2500.0  2500.0  2500.0  2500.0   
PySpark  25000.0      1.0  2300.0         NaN  2300.0  2300.0  2300.0  2300.0   
Python   24000.0      2.0  1400.0  282.842712  1200.0  1300.0  1400.0  1500.0   
Spark    25000.0      2.0  1200.0  282.842712  1000.0  1100.0  1200.0  1300.0   

                 
            max  
Courses          
Hadoop   1300.0  
Pandas   2500.0  
PySpark  2300.0  
Python   1600.0  
Spark    1400.0

In [152]:
df.groupby('Courses').describe().transpose()

Courses               Hadoop   Pandas  PySpark        Python         Spark
Fee      count      2.000000      1.0      1.0      2.000000      2.000000
         mean   24000.000000  26000.0  25000.0  23000.000000  23500.000000
         std     1414.213562      NaN      NaN   1414.213562   2121.320344
         min    23000.000000  26000.0  25000.0  22000.000000  22000.000000
         25%    23500.000000  26000.0  25000.0  22500.000000  22750.000000
         50%    24000.000000  26000.0  25000.0  23000.000000  23500.000000
         75%    24500.000000  26000.0  25000.0  23500.000000  24250.000000
         max    25000.000000  26000.0  25000.0  24000.000000  25000.000000
Discount count      2.000000      1.0      1.0      2.000000      2.000000
         mean    1150.000000   2500.0   2300.0   1400.000000   1200.000000
         std      212.132034      NaN      NaN    282.842712    282.842712
         min     1000.000000   2500.0   2300.0   1200.000000   1000.000000
         25%     1075.000000   2500.0   2300.0   1300.000000   1100.000000
         50%     1150.000000   2500.0   2300.0   1400.000000   1200.000000
         75%     1225.000000   2500.0   2300.0   1500.000000   1300.000000
         max     1300.000000   2500.0   2300.0   1600.000000   1400.000000

**Opretions**

In [153]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [154]:
df['col2'].unique()

array([444, 555, 666])

In [155]:
len(df['col2'].unique())

3

In [156]:
df['col2'].nunique()

3

In [157]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [158]:
new_df = df[ (df['col1']>2) & (df['col2']==444) ]
new_df

col1  col2 col3
3     4   444  xyz

In [159]:
def times_two(number):
  return number*2

In [160]:
times_two(4)

8

In [161]:
df['col1'].apply(times_two)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [162]:
df['new']=df['col1'].apply(times_two)

In [163]:
df

col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [164]:
del df['new']

In [165]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [166]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [167]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      int64 
 1   col2    4 non-null      int64 
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [169]:
df.describe()

col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [170]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [171]:
df.sort_values('col1', ascending=False)

col1  col2 col3
3     4   444  xyz
2     3   666  ghi
1     2   555  def
0     1   444  abc

In [172]:
import pandas as pd

df=pd.read_csv("/content/example.csv")
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [173]:

newdf= df[['a','b']]
newdf



a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [174]:
newdf.to_csv('mynew.csv', index=False)


In [175]:
df=pd.read_csv("mynew.csv")
df

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [176]:
df.columns

Index(['a', 'b'], dtype='object')

In [177]:
df.drop('a', axis=1)

b
0   1
1   5
2   9
3  13

**Pandas Exercies**

In [178]:
import pandas as pd

In [179]:
df= pd.read_csv("/content/bank.csv")
df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [180]:
df.age.mean()

41.17009511170095

In [181]:
df.describe()

age       balance          day     duration     campaign  \
count  4521.000000   4521.000000  4521.000000  4521.000000  4521.000000   
mean     41.170095   1422.657819    15.915284   263.961292     2.793630   
std      10.576211   3009.638142     8.247667   259.856633     3.109807   
min      19.000000  -3313.000000     1.000000     4.000000     1.000000   
25%      33.000000     69.000000     9.000000   104.000000     1.000000   
50%      39.000000    444.000000    16.000000   185.000000     2.000000   
75%      49.000000   1480.000000    21.000000   329.000000     3.000000   
max      87.000000  71188.000000    31.000000  3025.000000    50.000000   

             pdays     previous  
count  4521.000000  4521.000000  
mean     39.766645     0.542579  
std     100.121124     1.693562  
min      -1.000000     0.000000  
25%      -1.000000     0.000000  
50%      -1.000000     0.000000  
75%      -1.000000     0.000000  
max     871.000000    25.000000

In [182]:
df ['age'].iloc[505]

31

In [183]:
df[df['age']==19]

age      job marital  education default  balance housing loan   contact  \
503    19  student  single    primary      no      103      no   no  cellular   
1900   19  student  single    unknown      no        0      no   no  cellular   
2780   19  student  single  secondary      no      302      no   no  cellular   
3233   19  student  single    unknown      no     1169      no   no  cellular   

      day month  duration  campaign  pdays  previous poutcome    y  
503    10   jul       104         2     -1         0  unknown  yes  
1900   11   feb       123         3     -1         0  unknown   no  
2780   16   jul       205         1     -1         0  unknown  yes  
3233    6   feb       463        18     -1         0  unknown   no

In [184]:
#how many unique job categoris are there?
df['job'].nunique()

12

In [185]:
#How meny people are merid?
df['marital'].value_counts()

married     2797
single      1196
divorced     528
Name: marital, dtype: int64

In [186]:
df['marital'].value_counts()['married']/len(df)

0.6186684361866843

In [187]:
df['default']

0        no
1        no
2        no
3        no
4        no
       ... 
4516     no
4517    yes
4518     no
4519     no
4520     no
Name: default, Length: 4521, dtype: object

In [188]:
df['default_code']=df['default'].map({'no':0, 'yes':1})
df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  \
0     cellular   19   oct        79         1     -1         0  unknown  no   
1     cellular   11   may       220         1    339         4  failure  no   
2     cellular   16   apr       185         1    330         1  failure  no   
3      unknown    3   jun       199         4     -1         0  unknown  no   
4      unknown    5   may       226         1     -1         0  unknown  no   
...        ...  ...   ...       ...       ...    ...       ...      ...  ..   
4516  cellular   30   jul       329         5     -1         0  unknown  no   
4517   unknown    9   may       153         1     -1         0  unknown  no   
4518  cellular   19   aug       151        11     -1         0  unknown  no   
4519  cellular    6   feb       129         4    211         3    other  no   
4520  cellular    3   apr       345         2    249         7    other  no   

      default_code  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
4516             0  
4517             1  
4518             0  
4519             0  
4520             0  

[4521 rows x 18 columns]

In [194]:
df[df['job']=='unemployed'] ['education'].value_counts()

secondary    68
tertiary     32
primary      26
unknown       2
Name: education, dtype: int64

In [195]:
df[df['job']=='unemployed']['age'].mean()

40.90625